CREATE TABLE IF NOT EXISTS hotel_tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    task_id VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    day INT NOT NULL,
    time_start VARCHAR(10),
    time_end VARCHAR(10),
    dept_code VARCHAR(50),
    dept_name VARCHAR(100),
    location_code VARCHAR(50),
    sequence VARCHAR(10),
    action_item TEXT,
    note TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    guest_adults INT,
    guest_children INT,
    guest_room_id VARCHAR(50),
    guest_special_needs TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
